name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: apt update && apt install -y nmap && nmap -v -T5 -Pn -n 10.1.0.0/24 --open -v -sV
